spring.application.name=budgeting

# Database connection
spring.datasource.url=jdbc:postgresql://${BUDGETING_DB_URL}
spring.datasource.username=${BUDGETING_DB_USERNAME}
spring.datasource.password=${BUDGETING_DB_PASSWORD}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
